// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DialogForm: typeof import('./src/components/header/DialogForm.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./src/components/menu/SubMenu.vue')['default']
    Table: typeof import('./src/components/table/Table.vue')['default']
  }
}
